package service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * RegisterService service = new RegisterService();
 * RegisterDelegate portType = service.getRegisterPort();
 * portType.register(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "RegisterService", targetNamespace = "http://logic.com/", wsdlLocation = "http://localhost:9999/ClouddataWebservice/RegisterPort?wsdl")
public class RegisterService extends Service {

	private final static URL REGISTERSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(service.RegisterService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = service.RegisterService.class.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:9999/ClouddataWebservice/RegisterPort?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://localhost:9999/ClouddataWebservice/RegisterPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		REGISTERSERVICE_WSDL_LOCATION = url;
	}

	public RegisterService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public RegisterService() {
		super(REGISTERSERVICE_WSDL_LOCATION, new QName("http://logic.com/",
				"RegisterService"));
	}

	/**
	 * 
	 * @return returns RegisterDelegate
	 */
	@WebEndpoint(name = "RegisterPort")
	public RegisterDelegate getRegisterPort() {
		return super.getPort(new QName("http://logic.com/", "RegisterPort"),
				RegisterDelegate.class);
	}

}
