package filecontentservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * filedecryptionService service = new filedecryptionService();
 * FiledecryptionDelegate portType = service.getFiledecryptionPort();
 * portType.filequery(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "filedecryptionService", targetNamespace = "http://logic.com/", wsdlLocation = "http://localhost:9999/ClouddataWebservice/filedecryptionPort?wsdl")
public class FiledecryptionService extends Service {

	private final static URL FILEDECRYPTIONSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(filecontentservice.FiledecryptionService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = filecontentservice.FiledecryptionService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:9999/ClouddataWebservice/filedecryptionPort?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://localhost:9999/ClouddataWebservice/filedecryptionPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		FILEDECRYPTIONSERVICE_WSDL_LOCATION = url;
	}

	public FiledecryptionService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public FiledecryptionService() {
		super(FILEDECRYPTIONSERVICE_WSDL_LOCATION, new QName(
				"http://logic.com/", "filedecryptionService"));
	}

	/**
	 * 
	 * @return returns FiledecryptionDelegate
	 */
	@WebEndpoint(name = "filedecryptionPort")
	public FiledecryptionDelegate getFiledecryptionPort() {
		return super.getPort(new QName("http://logic.com/",
				"filedecryptionPort"), FiledecryptionDelegate.class);
	}

}
