package queryservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "SearchqueryDelegate", targetNamespace = "http://logic.com/")
public interface SearchqueryDelegate {

	/**
	 * 
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "genQuery", targetNamespace = "http://logic.com/", className = "queryservice.GenQuery")
	@ResponseWrapper(localName = "genQueryResponse", targetNamespace = "http://logic.com/", className = "queryservice.GenQueryResponse")
	public String genQuery(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2,
			@WebParam(name = "arg3", targetNamespace = "") String arg3);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<java.lang.Integer>
	 */
	@WebMethod(operationName = "bubble_srt")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "bubble_srt", targetNamespace = "http://logic.com/", className = "queryservice.BubbleSrt")
	@ResponseWrapper(localName = "bubble_srtResponse", targetNamespace = "http://logic.com/", className = "queryservice.BubbleSrtResponse")
	public List<Integer> bubbleSrt(
			@WebParam(name = "arg0", targetNamespace = "") List<Integer> arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "genQueryView", targetNamespace = "http://logic.com/", className = "queryservice.GenQueryView")
	@ResponseWrapper(localName = "genQueryViewResponse", targetNamespace = "http://logic.com/", className = "queryservice.GenQueryViewResponse")
	public String genQueryView(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2);

}
