package queryservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * SearchqueryService service = new SearchqueryService();
 * SearchqueryDelegate portType = service.getSearchqueryPort();
 * portType.genQuery(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "SearchqueryService", targetNamespace = "http://logic.com/", wsdlLocation = "http://localhost:9999/ClouddataWebservice/SearchqueryPort?wsdl")
public class SearchqueryService extends Service {

	private final static URL SEARCHQUERYSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(queryservice.SearchqueryService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = queryservice.SearchqueryService.class.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:9999/ClouddataWebservice/SearchqueryPort?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://localhost:9999/ClouddataWebservice/SearchqueryPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SEARCHQUERYSERVICE_WSDL_LOCATION = url;
	}

	public SearchqueryService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public SearchqueryService() {
		super(SEARCHQUERYSERVICE_WSDL_LOCATION, new QName("http://logic.com/",
				"SearchqueryService"));
	}

	/**
	 * 
	 * @return returns SearchqueryDelegate
	 */
	@WebEndpoint(name = "SearchqueryPort")
	public SearchqueryDelegate getSearchqueryPort() {
		return super.getPort(new QName("http://logic.com/", "SearchqueryPort"),
				SearchqueryDelegate.class);
	}

}
