package uploadservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * FileUploadService service = new FileUploadService();
 * FileUploadDelegate portType = service.getFileUploadPort();
 * portType.upload(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "FileUploadService", targetNamespace = "http://logic.com/", wsdlLocation = "http://localhost:9999/ClouddataWebservice/FileUploadPort?wsdl")
public class FileUploadService extends Service {

	private final static URL FILEUPLOADSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(uploadservice.FileUploadService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = uploadservice.FileUploadService.class.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:9999/ClouddataWebservice/FileUploadPort?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://localhost:9999/ClouddataWebservice/FileUploadPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		FILEUPLOADSERVICE_WSDL_LOCATION = url;
	}

	public FileUploadService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public FileUploadService() {
		super(FILEUPLOADSERVICE_WSDL_LOCATION, new QName("http://logic.com/",
				"FileUploadService"));
	}

	/**
	 * 
	 * @return returns FileUploadDelegate
	 */
	@WebEndpoint(name = "FileUploadPort")
	public FileUploadDelegate getFileUploadPort() {
		return super.getPort(new QName("http://logic.com/", "FileUploadPort"),
				FileUploadDelegate.class);
	}

}
